[general]
GROQ_API_KEY = "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"
NEO4J_URI="neo4j+s://36970dd4.databases.neo4j.io"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="1jLd1EMfvcf-sIZE3_RmSm9dx4VEwUa41abKDwNR1RM"
