GROQ_API_KEY = "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"
NEO4J_URI="neo4j+s://e205ecc7.databases.neo4j.io"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="2bU-osal1gE_Hfd6mcyacolzspn5Z2t-Nmeidjxc9Rc"
