GROQ_API_KEY = "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"
NEO4J_URI="neo4j+s://df57ae64.databases.neo4j.io"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="EdUtNpzk3ZYjrhZ9Z4E64GsrJmpeO4NJfMzQzSWQr3I"
