GROQ_API_KEY = "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"
OPENAI_API_KEY = "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"
NEO4J_URI="neo4j+s://52d416dc.databases.neo4j.io"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="lU8DREIuW-EHwSIDWSkuWK6j81QO8RFFkUd_JvCkOqs"
